wireplumber.settings = {
  log.level = 2
}

wireplumber.profiles = {
  main = {
    monitor.alsa = required
    monitor.bluez = disabled
    monitor.v4l2 = disabled
    monitor.libcamera = disabled
  }
}
