# Full replacement of default module list with dbus-free minimal core
context.modules = [
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-profiler }
    { name = libpipewire-module-metadata }

    { name = libpipewire-module-spa-device-factory }
    { name = libpipewire-module-spa-node-factory }

    { name = libpipewire-module-client-node }
    { name = libpipewire-module-client-device }

    { name = libpipewire-module-access args = { access.allowed = [ "all" ] } }
    { name = libpipewire-module-adapter }
    { name = libpipewire-module-link-factory }
    { name = libpipewire-module-session-manager }
]
